### ISSUE TITLE
Factory configuration loads into Razer System Recovery

### ISSUE THREAD

**Issue by deftdawg** [vampjaz/razer_blade_stealth_hackintosh#15]
I have a factory configured laptop on my hands and spent a few hours wondering if my UEFI booting was broken because each time I would select the UEFI USB device from the boot menu (`F12`), I would be taken into the `Razer System Recovery`.

![razer-system-recovery](https://user-images.githubusercontent.com/4991612/136046253-07c462e1-1638-4e6e-8980-9f81dc207405.jpg)

After a while I figured out that maybe OpenCore was defaulting to the first windows partition, so I went into `EFI/OC/config.plist` and set `ShowPicker` to `true`, that confirmed my suspicion.

![show-picker](https://user-images.githubusercontent.com/4991612/136046505-b3230bca-6db1-4fb1-9c1f-b579c0f59fe8.jpg)

After enabling `ShowPicker`, I was able to select `Install macOS` and the OSX recovery image loaded correctly.

**Suggestion:**  add this step to modify `ShowPicker` as a installation step to the readme for the benefit of other newbies.  😉

**Comment by vampjaz** [comment]
Sorry, I'm not adding steps as this isn't a guide.

**Comment by deftdawg** [comment]
That's fair enough... 🍻
