### ISSUE TITLE
I'm new to laptop hackintoshing

### ISSUE THREAD

**Issue by raphaelfalc** [vampjaz/razer_blade_stealth_hackintosh#3]
So, I got your EFI folder and put it in my usb install but all I'm getting is a white prohibited sign, can you help me with that? Also, I'm trying to hackintosh a razer blade stealth late 2017, gunmetal with pretty much the same specs as you except I don't know if my SSD is compatible, because I was trying to install macOS using a different guide for a 2016 model and my installation would always reboot at the last 2 mins of it (75% of the bar).

**Comment by raphaelfalc** [comment]
Update: Tried a SATA Samsung 860 Evo and it worked! I guess my 2017 model came with a PM981 ssd then.

**Comment by alinach120602** [comment]
Requesting close :)
