### ISSUE TITLE
Trackpad could not found after 10.14.6 security update

### ISSUE THREAD

**Issue by TMDeater** [vampjaz/razer_blade_stealth_hackintosh#6]
I freshly install Mac OS 10.16.4 where all works fine.
But the trackpad could not be found after 10.14.6 security update.

**Comment by burnburnrocket** [comment]
Try rebuilding your kext cache. `sudo kextcache -i /` from the terminal. After rebuild and reboot, the trackpad should start working again.

**Comment by TMDeater** [comment]
got works again, thanks
