### ISSUE TITLE
can't sleep...

### ISSUE THREAD

**Issue by gse356** [vampjaz/razer_blade_stealth_hackintosh#8]
Hi Hi, great guide and love this laptop I've gotten a bunch of desktop Hackintosh's going and this is my first attempt at a laptop build. The touch screen makes all the difference. Don't think I can ever got back to my MacBook. 

For some reason I cannot get the sleep to work and literally keeping me up at night....

I followed the guide and the sleep solutions described and handled the edits both manually and by copying the latest posted EFI.

When I copied it, my trackpad didn't work and the screen wouldn't comeback after closing the lid. Trackpad I solved with the voodoo kexts. No luck on the sleep...With the manual edits, no luck either.

With my current set up, when I close the lid or initiate sleep from the menu bar, screen blanks out and after about 20 seconds the Razer logo shuts and the side LED indicator flickers from green to white, then the logo comes back on and the LED goes back to green. Then when I open the lid or hit the keyboard it takes a bout 10 seconds for the screen to turn on and the login screen to appear. So it seems its trying to initiate sleep but something is preventing it. I think its associated with USBs not being abe to eject but not sure and cannot seem to adjust the USBInjectAll.kext to make it work. 

Attached a debug file if that helps. 

Any insight would be greatly appreciated. 

[debug_21883.zip](https://github.com/red-green/razer_blade_stealth_hackintosh/files/4776739/debug_21883.zip)

**Comment by gse356** [comment]
anyone?

**Comment by burnburnrocket** [comment]
Would recommend comparing earlier versions of the clover config. I had some issues with the most recent commit set and rolled back to my own version of the previous one.

**Comment by gse356** [comment]
wow, greatly appreciated! I went to this one that seemed to be the most relevant last stable's commit: 

https://github.com/red-green/razer_blade_stealth_hackintosh/tree/a2d930c40b7e28dddcd0ebbc0946144c69be530c

I got the sleep working right away but I cannot seem to get my trackpad working even after several kext cache rebuilds even with -f boot. 

Any thoughts on this?

**Comment by burnburnrocket** [comment]
Good to hear. I had decent luck with voodooi2c, just updating to the latest release from their own GitHub. Occasionally the trackpad goes nuts and moves the mouse around erratically, but sleeping/waking brings things back to normal.

**Comment by gse356** [comment]
cannot seem to get it to be allowed. check out the terminal screenshots in the mid section. (and yes experienced the possessed mouse many at time...)

![Screen Shot 2020-06-22 at 11 49 12 PM](https://user-images.githubusercontent.com/66913781/85359023-318b2580-b4e3-11ea-86d2-06bf6fe1d7dc.png)

![Screen Shot 2020-06-22 at 11 48 49 PM](https://user-images.githubusercontent.com/66913781/85359037-3a7bf700-b4e3-11ea-9228-2d609f723ab4.png)

**Comment by burnburnrocket** [comment]
I haven't run into this over here, but I also left my kexts in clover's kext folder, not inside of /L/E

**Comment by gse356** [comment]
I clean out the /L/E and populated the /clover/kexts/other accordingly with VoodooI2C.kext, VoodooI2CHID.kext and VoodooI2CSynaptics.kext - working perfectly. Finally, been a labor of love for the last 4 months...Thanks foe being there for me!

**Comment by gse356** [comment]
spoke too soon...when I try to mod to get the webcam working by either removing the SSDT-UIAC as described in the README.md or modifying to include it in the SSDT-UIAC (see file), I'm back to square one with sleep not working...Any insights?

**Comment by gse356** [comment]
wondering if it is possible to generate a script to initial the UIAC post boot to allow the webcam to run and another to deactivate to allow for sleep, in a similar fashion like one used to change the colors of keys....thoughts?

**Comment by burnburnrocket** [comment]
Hey there. I don't know if that would work, but I also wanna mention that my own USB setup with an earlier set of patches and older Clover config works fine and sleeps fine. I still think you can get all of this working by stepping back in the Clover and patch commits.

**Comment by gse356** [comment]
will definitely try it. can I trouble you to share your UAIC?

**Comment by burnburnrocket** [comment]
[SSDT-UIAC.aml.zip](https://github.com/red-green/razer_blade_stealth_hackintosh/files/4835154/SSDT-UIAC.aml.zip)

Here you go. Obviously you should disassemble this before trying it to make sure it looks reasonable for your system.

More importantly though, I looked though my notes, and I specifically made a point to roll back to the old SSDT-GPRW sleep fix that used to be in this repo, because sleep stopped working reliably for me with the new setup. I'm using that + the corresponding `sleep - rename GPRW definition to XPRW` Clover config entry here.

**Comment by vampjaz** [comment]
![image](https://user-images.githubusercontent.com/4503920/103837647-a15c9a00-5048-11eb-9a76-9d9e13143e07.png)

**Comment by super-triangle** [comment]
I don't think anyone mentioned Clover Configerator tho? There was discussion about the Clover install config.plist however.

**Comment by Mahasvan** [comment]
Plz help its 4am and i cant sleep either 😔
